# Site settings
title: Johannes Ippen
email: me@johannesippen.com
description: > # Johannes Ippen is a designer and author from Berlin, 
  Lead of Creative Services at Wooga and Founder at Thanksalot Design Collective.
baseurl: ""
url: "http://johannesippen.com"
twitter_username: presskind
exclude: ["/_sources/"]

# Build settings
markdown: kramdown
permalink: /:year/:title/