---
title: Johannes Ippen, Designer and Author
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: me@johannesippen.com
description: 'Head of Product Marketing at Wooga and Founder at Thanksalot Design
  Collective. New blog article every Wednesday.

'
baseurl: ''
url: http://johannesippen.com
twitter_username: presskind
exclude:
- "/_sources/"
- README.md
markdown: kramdown
permalink: "/:year/:title/"
kramdown:
  smart_quotes:
  - rdquo
  - rsquo
  - ldquo
  - rdquo
