# Site settings
title: Johannes Ippen, Designer and Author
email: me@johannesippen.com
description: > # This is the portfolio of designer and author Johannes Ippen from Berlin, 
  Head of Product Marketing at Wooga and Founder at Thanksalot Design Collective. New blog article every Wednesday.
baseurl: ""
url: "http://johannesippen.com"
twitter_username: presskind
exclude: ["/_sources/", "README.md"]

# Build settings
markdown: kramdown
permalink: /:year/:title/

kramdown:
    smart_quotes: ["rdquo", "rsquo", "ldquo", "rdquo"]